### PR TITLE
Simulator ignoring diagonal moves and corrected increase army interval

### PR DESCRIPTION
**Pull request by nosslin579**

### CODE REVIEW

**Comment by greenjoe** [comment]
Thank you, I've merged your pull request manually. I'm sorry it took so long, I took a break from working on this project.

**Comment by nosslin579** [comment]
No worries, it is just a fun project. BTW are you going to do a bot?

**Comment by greenjoe** [comment]
@nosslin579  I have a bot that uses this framework, bot itself is not open source though as the code is a mess. It's currently the best bot in the FFA "current" ranking http://bot.generals.io/profiles/[Bot]git.io%2Fsgts  :)

**Comment by nosslin579** [comment]
Cool, you should let it play regularly so other bots can play against it. And when I say other bots I mean my bots. :)

**Pull request closed without merging**
